### ISSUE TITLE
CYC-163 Add Vendor Feature Not Working

### ISSUE THREAD

**Issue by pascwhale** [m-triassi/soen390-team13#160]
## Expected Behavior

Form submission should add new supplier to the index.
## Actual Behavior

Submitting form does not update the table. There is a request error. 
## Steps to Reproduce

1. Go to supplier index
2. Fill out form
3. Submit form

**Comment by m-triassi** [comment]
This seems to be due to an improper date time being passed for the partnership start and end dates
```
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '2021-04-07T21:41:02.049Z' for column 'partnership_start_date' at row 1 (SQL: insert into `suppliers` (`name`, `partnership_start_date`, `partnership_end_date`, `updated_at`, `created_at`) values (test, 2021-04-07T21:41:02.049Z, 2021-04-14T21:41:04.061Z, 2021-04-07 21:41:05, 2021-04-07 21:41:05))
```

**Comment by m-triassi** [comment]
I can probably remedy this via the back-end, so ill just do that!
