### ISSUE TITLE
CYC-88 Integrate authentication to application router

### ISSUE THREAD

**Issue by IanjhPhillips** [m-triassi/soen390-team13#47]
[CYC-88](https://soen390team13.atlassian.net/browse/CYC-88)

When a user is not authenticated, re-direct the user to /login

Once a user is logged in, re-direct the user to /

**Comment by willyyhuang** [comment]
refer to CYC-88 on jira

**Comment by m-triassi** [comment]
Additionally, this should add a catch all route that handled hard-reloading in the SPA context
